# ╭───────────────────────────────────────────╮
# │  Example printer config                   │
# │  printers:                                │
# │    examplePrinter:                        │
# │      driverName: "My Printer Driver"      │
# │      printMode: "cli"                     │
# │      acceptedKinds: ["pdf", "image"]      │
# │      pxSize: "800x1200"                   │
# │      density: "300"                       │
# │      cliCommand: "python"                 │
# │      cliArgs: ["printChan.py", "{file}"]  │
# ╰───────────────────────────────────────────╯

port: 80
testing: true

printers:
  zebra:
    driverName: "Zebra450"
    printMode: "pdfToPrinter"
    acceptedKinds: ["pdf", "image", "zip"]
    pxSize: "800x1200"
    density: "300"

  brotherLaser:
    driverName: "Brother2360DUSB"
    printMode: "unixPrint"
    acceptedKinds: ["pdf", "image"]
    pxSize: null
    density: null

  dymoLabel:
    driverName: "DYMO4XLUSB"
    printMode: "pdfToPrinter"
    acceptedKinds: ["image"]
    pxSize: "425x200"
    density: "200"
